export const FETCH_PROVIDER_REQUEST = 'FETCH_PROVIDER_REQUEST'
export const FETCH_PROVIDER_SUCCESS = 'FETCH_PROVIDER_SUCCESS'
export const FETCH_PROVIDER_FAILURE = 'FETCH_PROVIDER_FAILURE'
export const FETCH_SERVICE_PROVIDERS = 'FETCH_SERVICE_PROVIDERS'